export const homeObjOne = {
    id: 'about',
    lightBg: true,
    lightText: false,
    lightTextDesc: true,
    topLine: 'Premium Bank',
    headline: 'On limited Transactions',
    description: 'Get acceess to something without getting charged any fees',
    buttonLabel: 'Get started',
    imgStart: false,
    img: require('../../images/svg-1.svg').default,
    alt: 'Car',
    dark: true,
    primary: true,
    darkText: true,
}

export const homeObjTwo = {
    id: 'experience',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'Premium Bank',
    headline: 'On limited Transactions',
    description: 'Get acceess to something without getting charged any fees',
    buttonLabel: 'Get started',
    imgStart: true,
    img: require('../../images/svg-1.svg').default,
    alt: 'Car',
    dark: true,
    primary: true,
    darkText: false,
}

export const homeObjThree = {
    id: 'contactMe',
    lightBg: true,
    lightText: true,
    lightTextDesc: true,
    topLine: 'Premium Bank',
    headline: 'On limited Transactions',
    description: 'Get acceess to something without getting charged any fees',
    buttonLabel: 'Get started',
    imgStart: false,
    img: require('../../images/svg-1.svg').default,
    alt: 'Car',
    dark: true,
    primary: true,
    darkText: true,
}