export const homeObjOne = {
    id: 'about',
    lightBg: true,
    lightText: false,
    lightTextDesc: true,
    headline: 'About Rojaun:',
    description: 'I have a passion for learning new technologies that improve my developing skills as well as understanding others. Starting with small assignments in school, I\'ve now transitioned into working on independent projects. I aspire to work as a full stack developer creating products will change and improve lives.  ',
    buttonLabel: 'Resumé',
    imgStart: false,
    img: require('../../images/rojaunIcon.PNG').default,
    alt: 'rojaunIcon',
    dark: true,
    primary: true,
    darkText: true,
}

export const homeObjTwo = {
    id: 'experience',
    lightBg: false,
    lightText: false,
    lightTextDesc: true,
    topLine: 'Premium Bank',
    headline: 'On limited Transactions',
    description: 'Get acceess to something without getting charged any fees',
    buttonLabel: 'Get started',
    imgStart: true,
    img: require('../../images/svg-1.svg').default,
    alt: 'Car',
    dark: true,
    primary: true,
    darkText: false,
}

export const homeObjThree = {
    id: 'contactMe',
    lightBg: false,
    lightText: false,
    lightTextDesc: true,
    topLine: 'Premium Bank',
    headline: 'On limited Transactions',
    description: 'Get acceess to something without getting charged any fees',
    buttonLabel: 'Get started',
    imgStart: false,
    img: require('../../images/svg-1.svg').default,
    alt: 'Car',
    dark: true,
    primary: true,
    darkText: true,
}